### PR TITLE
Model context migration

### LINKED ISSUE #1: Add model classes
- Add model classes based on [https://app.diagrams.net/#G19ZqSZBC25tCEcYkW7XSAfc1lFc7NTNBt](url) document Model diagram.
- Add DbContext
- Add initial Migration

### PR DESCRIPTION
**Pull request by tercsd**
#1 solved.

### CODE REVIEW

**Review by timigyurina — APPROVED** [review]
Approved.

**Review by pityken — APPROVED** [review]
Seems good.

**Review by Quvasz — APPROVED** [review]
approved

**Comment by PlaveczAdam** [comment]
approved

**Pull request merged**
