### PR TITLE
3 create working endpoints for reservations module

### LINKED ISSUE #3: Create working endpoints for Reservations module
Create working endpoints for Reservations module including:

- Controller
- Repository

### PR DESCRIPTION
**Pull request by timigyurina**

### CODE REVIEW

**Review by Quvasz — APPROVED** [review]
ok

**Review by tercsd — APPROVED** [review]
looks good to me

**Review by PlaveczAdam — APPROVED** [review]
Approved

**Review by pityken — APPROVED** [review]
I approve this commit

**Pull request merged**
